#!/bin/bash
user=jani #launch as this user
hak=$(dirname $0)
export DISPLAY=:0
cd $hak/bin
sudo -u $user ./cechiiri &
pid_cechiiri=$!
sudo -u $user ./cectv2
kill -9 $(ps -o pid= --ppid $pid_cechiiri) 2>/dev/null && kill -9 $pid_cechiiri 2>/dev/null
